---
version: "3"
services:
  db:
    image: "postgres:12"
    ports: 
      - "5432:5432"
    volumes:
      - './seeds:/docker-entrypoint-initdb.d'
    environment:
      POSTGRES_DB: dotdotvote
      POSTGRES_PASSWORD: supersecretpassword
